#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "✨ Running pre-commit checks..."

# Run linting
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ Linting failed. Please fix the errors before committing."
  exit 1
else
  echo "✅ Linting successful!"
fi

# Run formatting
npm run prettier:format
if [ $? -ne 0 ]; then
  echo "❌ Formatting failed. Please fix the errors before committing."
  exit 1
else
  echo "✅ Formatting successful!"
fi

echo "🚀 All pre-commit checks passed. Proceeding with commit..."